version: '0.0.{build}'

image: Visual Studio 2017

init:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

configuration:
  - Debug
  - Release

environment:
  matrix:
  - arch: x86
    platform: Win32
    visual_studio: Visual Studio 15 2017
    gtest: 1.7.0
    boost: 1.66.0
    OpenSSL: 1.0.2n

  - arch: x86_64
    platform: x64
    visual_studio: Visual Studio 15 2017 Win64
    gtest: 1.8.1
    boost: 1.67.0
    OpenSSL: 1.0.2n

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

before_build:
  - md build
  - cd build
  - conan install .. -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -o gtest=%GTEST% -o boost=%BOOST% -o OpenSSL=%OPENSSL%
  - cmake .. -G "%VISUAL_STUDIO%"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\BoostAsioWebServerAdapter.sln

after_build:
  - conan export-pkg ../conanfile.py BoostAsioWebServerAdapter/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -o gtest=%GTEST% -o boost=%BOOST% -o OpenSSL=%OPENSSL%
  - conan test ../test_package/conanfile.py BoostAsioWebServerAdapter/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=v141 -s arch=%ARCH% -o gtest=%GTEST% -o boost=%BOOST% -o OpenSSL=%OPENSSL%

test_script:
  - ps: cd bin
  - ps: cd $env:CONFIGURATION
  - BoostAsioWebServerAdapterTest.exe --gtest_output=xml:BoostAsioWebServerAdapterTest.xml

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\BoostAsioWebServerAdapterTest.xml))

artifacts:
  - path: 'build\lib\%CONFIGURATION%\BoostAsioWebServerAdapter.lib'
    name: BoostAsioWebServerAdapter.lib

deploy_script:
  - ps: >- 
      if($env:appveyor_repo_tag -eq 'True') {
        conan upload BoostAsioWebServerAdapter/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
      } else {
        echo "Not uploading because this is not a tag build"
      }
