language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Release
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Coverage
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - os: osx
    osx_image: xcode10.1
    compiler: clang   
    env:
      - BUILD_TYPE=Release

install: 
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
  - if [[ $TRAVIS_OS_NAME == linux && $BUILD_TYPE == Coverage ]]; then sudo apt-get install lcov; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then pip install conan --user; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install conan; fi
  - conan user

script:    
  - g++ --version
  - mkdir -p build
  - cd build
  - conan install ..
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make
  - cd bin
  - ls
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo cp *.dylib /usr/local/lib; fi
  - ./BoostAsioWebServerAdapterTest
  - cd ..
  - if [[ $TRAVIS_OS_NAME == linux && $BUILD_TYPE == Coverage ]]; then make BoostAsioWebServerAdapterTestCoverage; fi
  - cd test
  - cd BoostAsioWebServerAdapterTest
  - ctest

after_success:
  - if [[ $TRAVIS_OS_NAME == linux && $BUILD_TYPE == Coverage ]]; then bash <(curl -s https://codecov.io/bash); fi
